dist: xenial
language: python
python:
  - "3.7"
install:
- pip install -r requirements.txt
script: pytest
deploy:
  provider: lambda
  function_name: "travistest"
  region: "eu-north-1"
  role: $ROLE
  runtime: "python3.7"
  module_name: api/app
  handler_name: handler
